version: '3.1'

services:
    edmos_db:
        container_name: edmos-db
        image: mysql:5.7
        restart: always
        networks:
            - default
        environment: 
            MYSQL_DATABASE: edmerpdb
            MYSQL_USER: edmoserp
            MYSQL_PASSWORD: edmoserp@2020
            MYSQL_ROOT_PASSWORD: admin@123
        volumes: 
            - edmos-mysql:/var/lib/mysql

    edmos_dolibarr:
        container_name: edmos-dolibarr
        build: .
        image: edmos-erp:latest
        restart: always
        ports:
            - 80:80
        networks:
            - default
        environment: 
            DOLI_DB_HOST: edmos_db 
            DOLI_DB_USER: edmoserp
            DOLI_DB_PASSWORD: edmoserp@2020
            DOLI_DB_ROOT_PASSWORD: edmoserp@2020
            DOLI_DB_NAME: edmerpdb
            PHP_INI_DATE_TIMEZONE: 'America/Sao_Paulo'
        depends_on:
            - edmos_db
        volumes: 
            - edmos-dolibarr:/var/www/html
            - edmos-dolibarr:/var/www/documents
            - edmos-dolibarr:/var/www/html/theme
            - edmos-dolibarr:/var/www/html/conf
            - edmos-dolibarr:/var/www/html/custom

networks:
    default:

volumes: 
    edmos-dolibarr:
    edmos-mysql:
